name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: []}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}
          
            output_action: commit
            committer_branch: dist
            committer_message: "[Metrics Update] Updating Picture"

            user: mcalec1
            template: classic
            base: header, activity, community, repositories, metadata
            
            config_timezone: America/New_York
            config_display: columns
            config_base64: yes
            
            plugin_achievements: yes
            plugin_achievements_secrets: yes
            plugin_achievements_display: compact
            plugin_achievements_threshold: B
            plugin_achievements_limit: 5
            
            plugin_pagespeed: yes
            lugin_pagespeed_url: mcalec.dev
            
            plugin_wakatime: yes
            plugin_wakatime_token:  ${{ secrets.WAKATIME_API }}
            plugin_wakatime_days: 30
            plugin_wakatime_limit: 5
            plugin_wakatime_repositories_visibility: all
            plugin_wakatime_sections: time, languages, languages-graphs, editors, os
            plugin_wakatime_url: https://wakatime.com
            plugin_wakatime_user: current
            